#=
# [Kazmierczak et al 2024](@id Kazmierczak2024)
This is an example of how to run the FastHydrology.jl package for the steady state problem of
Kazmierczak et al 2024 (https://doi.org/10.5194/tc-18-5887-2024).

The figures below come from running this model on the Thwaites Amundsen-sector dataset used for
Fig. S3 of Kazmierczak et al 2024, on a hard bed (`bed_rheology = :hard`). They were made when the
model took KORI-ULB's converged melt rate as input; the script now builds the melt rate from its
terms instead, so its output differs from these figures until they are regenerated.

## Reproducing these figures

The input file (`THWAITES2km_m3_HAB_toto.mat`, ~90 MB) is not shipped with this repository, so that
cloning/installing FastHydrology.jl stays lightweight -- this page is built from the static figures
below rather than by running the pipeline live. To reproduce them yourself:

1. Obtain `THWAITES2km_m3_HAB_toto.mat` and place it at
   `docs/src/examples/input/Kazmierczak2024/THWAITES2km_m3_HAB_toto.mat`.
2. Run the script below directly with `julia` (it is shown for reference only -- the docs build
   does not execute it):

```julia
using FastHydrology
using CairoMakie

T = Float64
path = joinpath(@__DIR__, "input", "Kazmierczak2024", "THWAITES2km_m3_HAB_toto.mat")
Nx, Ny, xlims, ylims, mask, h, b, abs_v_b, A_visc, G, q_T, tau_b, κ = load_Kazmierczak(path; bed_rheology = :hard)

# Prepare a grid backed by plain arrays, and visualize it.
grid = ArrayHydroGrid(Nx, Ny, xlims, ylims; T = T)
fig = visualize_grid(grid)

# Build the model using the data from the input file above. The model holds its model-specific
# fields, with the rest of the fields common to all models stored in the HydroState below.
#
# The water source is built from the terms of Eq. 3 of Kazmierczak et al 2024: the geothermal heat `G`,
# the conductive heat into the ice `q_T` (from KORI-ULB's basal temperature gradient) and the frictional
# heat `tau_b*|u_b|`, with `tau_b` KORI-ULB's own `taudxy` passed through `PrescribedFieldSlidingLaw`.
#
# By default, the water source feeding the flux-routing algorithm also includes the dissipation melt
# rate generated by the flux itself as it moves down the hydraulic gradient (`dissipation_melt =
# true`) -- a term Kazmierczak et al 2024 drop as negligible but which is kept here for
# generality. It can be turned off with `dissipation_melt = false` to reproduce the paper's
# original water balance exactly. We also silence the per-call Picard convergence printout here
# with `dissipation_verbose = false`.
#
# `coupling_length_kamb86` is Kamb & Echelmeyer (1986)'s stress-gradient-coupling length, passed
# directly as a multiple of ice thickness (~4-10 for ice sheets, ~1-3 for valley/mountain glaciers --
# see the constructor's docstring). It has no safe default that works for every grid resolution, so it
# must be passed explicitly or `KazmierczakHydroModel` warns and falls back to 10.0 (the upper edge of
# the ice-sheet range). 10.0 is appropriate for this dataset's 2 km grid.
#
# `state.W`'s closure (`water_thickness_algorithm`, default `DarcyWeisbachThickness()`) and its
# numerical-safety bounds (`Wmin`/`Wmax`/`q_max`/`sigmat`, all no-op by default -- nothing is
# clamped unless you ask for it) are left at their defaults here; see the API reference for the
# other closures (`ArealConduitThickness`, `LaminarThickness`) and KORI-ULB's own bound values.
model = KazmierczakHydroModel(grid, κ, abs_v_b, A_visc, G, q_T; sliding_law = PrescribedFieldSlidingLaw(grid, tau_b),
                              coupling_length_kamb86 = 10.0, dissipation_verbose = false)
state = HydroState(grid, mask, h, b)
sim   = SteadyStateSimulation(model, grid, state)
run!(sim)

# Rescale for plotting.
model.q .*= perSecond2perYear(1.0) / 1e4 # makes q [10⁴ m² a⁻¹]
state.N .*= 1e-6 # makes N [MPa]
model.q .= mask_field(model.q, state.mask, NaN)
state.N .= mask_field(state.N, state.mask, NaN)
state.W .= mask_field(state.W, state.mask, NaN)

fig_q = visualize_field(grid, model.q; plot_title = "Distributed water flux q [10⁴ m² a⁻¹]", transpose_data = true, colorrange = (0, 10))
fig_W = visualize_field(grid, state.W; plot_title = "Water thickness W [m] (DarcyWeisbachThickness)", transpose_data = true, colorrange = extrema(filter(!isnan, state.W)))
fig_N = visualize_field(grid, state.N; plot_title = "Effective pressure N [MPa]", transpose_data = true, colorrange = (0, 10))

# ## Adding a basal sliding law
#
# Above, `tau_b` was a given field. Passing a pressure-dependent sliding law instead computes the
# frictional-heating term tau_b*v_b/L_w (Eq. 3 of Kazmierczak et al 2024) from a basal shear stress
# `tau_b(N, v_b)`.Since tau_b then depends on the effective pressure N, which is
# itself downstream of q, `resolve_q!` widens its Picard loop to solve for q and N jointly rather than
# nesting a second loop around the first -- see the `sliding_law` keyword on `KazmierczakHydroModel`
# and `resolve_q!`'s docstring for the physics and the loop design.
#
# `PowerPlasticSlidingLaw` and `RegularizedCoulombSlidingLaw` are written to match the two sliding
# laws implemented in Yelmo.jl's `basal_dragging.jl` (`beta_method` 1/2/4 and 3/5 respectively), so
# a future ice-dynamics coupling can configure both sides with numerically matching laws. The
# parameters below (`c_till`, `q`, `u0`) are illustrative, not calibrated to Thwaites.
#
sliding_law = RegularizedCoulombSlidingLaw(c_till = 0.5, q = 1/3, u0 = perYear2perSecond(100.0))
model_sliding = KazmierczakHydroModel(grid, κ, abs_v_b, A_visc, G, q_T;
                                       sliding_law = sliding_law, coupling_length_kamb86 = 10.0,
                                       dissipation_verbose = false, qN_verbose = false)
state_sliding = HydroState(grid, mask, h, b)
run!(SteadyStateSimulation(model_sliding, grid, state_sliding))

model_sliding.tau_b .*= 1e-6 # makes tau_b [MPa]
model_sliding.tau_b .= mask_field(model_sliding.tau_b, state_sliding.mask, NaN)
fig_tau_b = visualize_field(grid, model_sliding.tau_b; plot_title = "Basal shear stress tau_b [MPa]", transpose_data = true, colorrange = extrema(filter(!isnan, model_sliding.tau_b)))

# ## The terms of the melt rate
#
# Each term is kept as its own field [W/m^2]: `model.G`, `model.q_T`, `model.Q_b` (friction),
# `model.Q_diss` (dissipation), plus the water from above `model.i_eb` [kg/m^2/s]. `set_basal_terms!` updates the
# given ones between solves, e.g. when coupled to an ice-sheet model. KORI-ULB's own melt rate is
# available from `load_Kazmierczak_melt` for comparison only: rebuilt from these terms it matches in a
# typical cell, but its total over this domain is about twice the sum of the terms, the difference
# coming from a few percent of the cells.
Q_terms = (model.G, model.q_T, model.Q_b, model.Q_diss)
mdot_kori = load_Kazmierczak_melt(path)
```

## Results

Distributed water flux q [10⁴ m² a⁻¹]:

![Distributed water flux](figures/Kaz24_thwaites_q.png)

Water thickness W [m]:

![Water thickness](figures/Kaz24_thwaites_W.png)

Effective pressure N [MPa]:

![Effective pressure](figures/Kaz24_thwaites_N.png)

Basal shear stress tau_b [MPa], with `RegularizedCoulombSlidingLaw`:

![Basal shear stress](figures/Kaz24_thwaites_tau_b.png)
=#
nothing #hide
